# Generated by Django 2.2.7 on 2019-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20191129_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='rank',
            field=models.CharField(choices=[('New member', 'Новичек'), ('Silver', 'Серебро'), ('Gold', 'Золото'), ('Platinum', 'Платина')], default='STARTER', max_length=15, verbose_name='Уровень клубной карты'),
        ),
    ]
