# Generated by Django 2.2.7 on 2019-12-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20191202_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksrent',
            name='book_renter',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
