# Generated by Django 2.2.7 on 2019-12-03 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p_library', '0005_auto_20191203_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksrent',
            name='book_renter',
            field=models.OneToOneField(blank=True, help_text='Помните, что 1 пользователь может взять 1 книгу!', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Арендатор'),
        ),
    ]
